from os import path
from trafficmon.globals import TrafficmonGlobals


TRAFFICMON_CONIFG_FILENAME = "traffic-monitor/src/common/global-vars.h"
TRAFFICMON_CONFIG : dict[str, str] = {
    item.name: str(item.value) for item in TrafficmonGlobals
}

# Test if a string is a valid C identifier
def is_valid_c_identifier(s: str) -> bool:
    return s.isidentifier()

# Create the file contents
file_contents: str = '\n'.join([
    '// This file is auto-generated by pre-compile.py. Do not edit.',
    '',
    *(
        f'#define {key} {value}' for key, value in TRAFFICMON_CONFIG.items()
    ),
    ''
])

# Compare file contents. Only overwrite if different.
old_contents = None
if path.exists(TRAFFICMON_CONIFG_FILENAME):
    with open(TRAFFICMON_CONIFG_FILENAME, 'r') as f:
        old_contents = f.read()

if old_contents == file_contents:
    print(f"File {TRAFFICMON_CONIFG_FILENAME} is up to date.")
else:
    with open(TRAFFICMON_CONIFG_FILENAME, 'w') as f:
        f.write(file_contents)
    print(f"File {TRAFFICMON_CONIFG_FILENAME} has been updated.")