from os import path
from trafficmon.globals import TrafficmonGlobals


TRAFFICMON_CONIFG_FILENAME = "traffic-monitor/src/common/global-vars.h"
TRAFFICMON_CONFIG : dict[str, str] = {
    k: str(v)
    for k, v in TrafficmonGlobals.__dict__.items()
    if not k.startswith('_')
}

# Test if a string is a valid C identifier
assert all(
    key.isidentifier() and '\n' not in value
    for key, value in TRAFFICMON_CONFIG.items()
), "Invalid Trafficmon Globals (see trafficmon/globals.py)"

# Create the file contents
file_contents: str = '\n'.join([
    '// This file is auto-generated by pre-compile.py. Do not edit.',
    '',
    *(
        f'#define {key} {value}' for key, value in TRAFFICMON_CONFIG.items()
    ),
    ''
])

# Compare file contents. Only overwrite if different.
old_contents = None
if path.exists(TRAFFICMON_CONIFG_FILENAME):
    with open(TRAFFICMON_CONIFG_FILENAME, 'r') as f:
        old_contents = f.read()

if old_contents == file_contents:
    print(f"File {TRAFFICMON_CONIFG_FILENAME} is up to date.")
else:
    with open(TRAFFICMON_CONIFG_FILENAME, 'w') as f:
        f.write(file_contents)
    print(f"File {TRAFFICMON_CONIFG_FILENAME} has been updated.")